//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliqmachinemapping
    {
        public long id { get; set; }
        public long BranchID { get; set; }
        public long Test_ID { get; set; }
        public string TestName { get; set; }
        public long CliqAttributeID { get; set; }
        public string AttributeName { get; set; }
        public string MachineAttributeCode { get; set; }
        public bool Active { get; set; }
        public long MachineID { get; set; }
    
        public virtual mi_tinstruments mi_tinstruments { get; set; }
    }
}
