//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mi_tinstruments
    {
        public mi_tinstruments()
        {
            this.cliqmachinemappings = new HashSet<cliqmachinemapping>();
        }
    
        public long InstrumentID { get; set; }
        public long Supplierid { get; set; }
        public string Instrument_Name { get; set; }
        public string Model { get; set; }
        public string I_Release { get; set; }
        public string Description { get; set; }
        public string Manual { get; set; }
        public string Patient_no_format { get; set; }
        public string BarCode_Standard { get; set; }
        public string Bidirectional { get; set; }
        public string Communication_Stnadard { get; set; }
        public string Communication_method { get; set; }
        public string PORT { get; set; }
        public long BaudRate { get; set; }
        public string Parity { get; set; }
        public string Stopbit { get; set; }
        public string DataBit { get; set; }
        public string FlowControl { get; set; }
        public Nullable<long> Acknowledgement_code { get; set; }
        public long EnteredBy { get; set; }
        public System.DateTime EnteredOn { get; set; }
        public string ClientID { get; set; }
        public string Active { get; set; }
    
        public virtual ICollection<cliqmachinemapping> cliqmachinemappings { get; set; }
    }
}
