//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mi_tresult
    {
        public mi_tresult()
        {
            this.mi_taudit = new HashSet<mi_taudit>();
        }
    
        public long ResultID { get; set; }
        public string BookingID { get; set; }
        public string AttributeID { get; set; }
        public string Result { get; set; }
        public long EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public string ClientID { get; set; }
        public string Status { get; set; }
        public string machinename { get; set; }
        public Nullable<System.DateTime> senton { get; set; }
        public string sentto { get; set; }
    
        public virtual ICollection<mi_taudit> mi_taudit { get; set; }
    }
}
