//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mi_tsuppliers
    {
        public long SupplierID { get; set; }
        public string Supplier_Name { get; set; }
        public string Address { get; set; }
        public string Phone_1 { get; set; }
        public string Phone_2 { get; set; }
        public string Fax_1 { get; set; }
        public string Fax_2 { get; set; }
        public string Email { get; set; }
        public string CellNo { get; set; }
        public string WebAddress { get; set; }
        public string Linkedin_ID { get; set; }
        public string CP_Name { get; set; }
        public string CP_Designation { get; set; }
        public string CP_Office_Phone { get; set; }
        public string CP_Cell_no { get; set; }
        public string CP_Email { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public long EnteredBy { get; set; }
        public System.DateTime EnteredOn { get; set; }
        public string Clientid { get; set; }
        public string Active { get; set; }
        public Nullable<long> Ref_SupplierID { get; set; }
    }
}
