//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mi_ttests
    {
        public long Machine_testid { get; set; }
        public string Lims_testid { get; set; }
        public string Lims_test_name { get; set; }
        public string Machine_Test_name { get; set; }
        public string LOINC_code { get; set; }
        public long Instrumentid { get; set; }
        public long EnteredBy { get; set; }
        public System.DateTime EnteredOn { get; set; }
        public string ClientID { get; set; }
        public string Active { get; set; }
        public string DeptID { get; set; }
        public string MachineTestCode { get; set; }
    }
}
