//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mi_tpreferencesetting
    {
        public long id { get; set; }
        public string serveraddress { get; set; }
        public string archivalfolderpath { get; set; }
        public string serverfolderpath { get; set; }
        public string serveruser { get; set; }
        public string serverpassword { get; set; }
        public string transfer_method { get; set; }
        public string status { get; set; }
    }
}
