//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mi_tpersonnel
    {
        public long PersonId { get; set; }
        public string OrgId { get; set; }
        public long DepartmentId { get; set; }
        public long SubdepartmentId { get; set; }
        public long DesignationId { get; set; }
        public string Active { get; set; }
        public string ServiceNo { get; set; }
        public string Salutation { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string Acronym { get; set; }
        public string FHName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string BloodGroup { get; set; }
        public string MS { get; set; }
        public string NIC { get; set; }
        public Nullable<System.DateTime> NICValidUpto { get; set; }
        public string Passport { get; set; }
        public Nullable<System.DateTime> PassportValidUpto { get; set; }
        public string HPhoneNo1 { get; set; }
        public string HPhoneNo2 { get; set; }
        public string OPhoneNo1 { get; set; }
        public string OPhoneNo2 { get; set; }
        public string CPhoneNo { get; set; }
        public string Email { get; set; }
        public string CurrentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string PictureRef { get; set; }
        public string LoginId { get; set; }
        public string Pasword { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string Education { get; set; }
        public string Nature { get; set; }
        public Nullable<System.DateTime> ContractExpiry { get; set; }
        public string ReferenceCode { get; set; }
        public Nullable<long> Salary { get; set; }
        public string FaxNo { get; set; }
        public long Enteredby { get; set; }
        public System.DateTime Enteredon { get; set; }
        public string clientid { get; set; }
        public string crossdept { get; set; }
    }
}
