//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mi_taudit
    {
        public long id { get; set; }
        public Nullable<System.DateTime> senton { get; set; }
        public string sentto { get; set; }
        public string filename { get; set; }
        public string status { get; set; }
        public long maxresultid { get; set; }
    
        public virtual mi_tresult mi_tresult { get; set; }
    }
}
