//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class miEntities : DbContext
    {
        public miEntities()
            : base("name=miEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mi_setting> mi_setting { get; set; }
        public DbSet<mi_taudit> mi_taudit { get; set; }
        public DbSet<mi_tbooking> mi_tbooking { get; set; }
        public DbSet<mi_tinstruments> mi_tinstruments { get; set; }
        public DbSet<mi_tpersonnel> mi_tpersonnel { get; set; }
        public DbSet<mi_tpreferencesetting> mi_tpreferencesetting { get; set; }
        public DbSet<mi_tresult> mi_tresult { get; set; }
        public DbSet<mi_tsuppliers> mi_tsuppliers { get; set; }
        public DbSet<mi_ttestattribute> mi_ttestattribute { get; set; }
        public DbSet<mi_ttests> mi_ttests { get; set; }
        public DbSet<cliqmachinemapping> cliqmachinemappings { get; set; }
    }
}
